[tools]
go = "latest"
node = { version = "latest", postinstall = "corepack enable" }
python = "3.13"
ruby = "latest"
ruff = "latest"
rust = "latest"
uv = "latest"

"gem:neovim" = "latest"
"npm:neovim" = "latest"

[settings]
env_file = ".env"
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[settings.python]
uv_venv_auto = true
uv_venv_create_args = ["--seed"]

[env]
_.python.venv = { path = ".venv" }
