[tools]
"gem:neovim" = "latest"
"npm:neovim" = "latest"
"pipx:mypy" = "latest"
bat = "latest"
colima = "latest"
docker-compose = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
hyperfine = "latest"
lazydocker = "latest"
lsd = "latest"
node = { version = "latest", postinstall = "corepack enable" }
python = "3.13"
ripgrep = "latest"
ruby = "latest"
ruff = "latest"
rust = "latest"
starship = "latest"
uv = "latest"
yazi = "latest"
zoxide = "latest"
java = "latest"
sqlite = "latest"

[settings]
env_file = ".env"
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[settings.python]
uv_venv_auto = true
uv_venv_create_args = ["--seed"]
