#!/usr/bin/env ruby
# frozen_string_literal: true

cask_args appdir: '/Applications' if OS.mac?

tap 'neovim/neovim' || true

brew 'bat'
brew 'btop'
brew 'colima'
brew 'coreutils'
brew 'docker'
brew 'docker-buildx'
brew 'docker-compose'
brew 'fd'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'git-delta'
brew 'htop'
brew 'hyperfine'
brew 'imagemagick'
brew 'lazydocker'
brew 'lsd'
brew 'neovim'
brew 'nvm'
brew 'ranger'
brew 'rbenv'
brew 'ripgrep'
brew 'starship'
brew 'stow'
brew 'tldr'
brew 'tmux'
brew 'tree'
brew 'uv'
brew 'yazi'
brew 'zoxide'

cask 'alt-tab'
cask 'bruno'
cask 'discord'
cask 'font-mononoki-nerd-font'
cask 'google-chrome'
cask 'hyperkey'
cask 'kitty'
cask 'protonvpn'
cask 'qbittorrent'
cask 'raycast'
cask 'sf-symbols'
cask 'slack'
cask 'spotify'
cask 'vlc'
