#!/bin/bash

# JankyBorders config: https://github.com/FelixKratz/JankyBorders
# Colors are 0xAARRGGBB.

options=(
	style=round
	width=6.0
	hidpi=on
	active_color="glow(0xffbf40ff)"
	inactive_color=0xff2a1b3d
)

borders "${options[@]}"
