#!/usr/bin/env sh

launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

"$HOME"/.config/yabai/create-spaces.sh

yabai -m config window_border                   on           
yabai -m config mouse_follows_focus             off          
yabai -m config focus_follows_mouse             off
yabai -m config window_zoom_persist             on          
yabai -m config window_placement                second_child 
yabai -m config window_opacity_duration         0.0         
yabai -m config active_window_opacity           1.0          
yabai -m config normal_window_opacity           1.0         
yabai -m config window_border_width             1            
yabai -m config window_border_hidpi             on          
yabai -m config window_animation_duration       0.0
yabai -m config mouse_drop_action               swap         
yabai -m config window_border_placement         exterior
yabai -m config window_border_radius            10
yabai -m config active_window_border_color      0xFFFFAA69
yabai -m config normal_window_border_color      0xFF73FFFD
yabai -m config insert_window_border_color      0xFF73FFFD
yabai -m config insert_feedback_color           0xff9dd274   
yabai -m config window_opacity                  off
yabai -m config split_ratio                     0.50
yabai -m config auto_balance                    on
yabai -m config mouse_modifier                  fn
yabai -m config mouse_action1                   move
yabai -m config mouse_action2                   resize
yabai -m config layout                          bsp
yabai -m config top_padding                     4
yabai -m config bottom_padding                  4
yabai -m config left_padding                    4
yabai -m config right_padding                   4
yabai -m config window_gap                      4
yabai -m config window_topmost                  off
yabai -m config window_border_blur              off

yabai -m space 1
yabai -m space 2
yabai -m space 3
yabai -m space 4
yabai -m space 5
yabai -m space 6

yabai -m rule --add app="^System Settings$"  manage=off border=off
